import {
  Activity, AlertTriangle,
  Baby,
  BookOpen, Briefcase, Brush,
  Car,
  Coffee, Coins, Construction, Crosshair, Dumbbell,
  Gamepad2, Gift, GraduationCap, Hammer, Heart, HeartPulse,
  Home, KeyRound, Landmark, Laptop, PawPrint, PiggyBank,
  Pizza,
  Plane, Radio, RefreshCw, Scale, Scissors, ShieldAlert, ShieldCheck,
  ShoppingBag, ShoppingCart,
  Sparkles, Ticket, TrendingUp,
  Tv,
  Users,
  Utensils, Wine, Wrench,
  Zap
} from "lucide-react-native";

export const CATEGORY_NAMES = [
  { id: "food", label: "Groceries", icon: Utensils, color: "#EF4444" },
  { id: "dining", label: "Dining Out", icon: Pizza, color: "#F97316" },
  { id: "coffee", label: "Coffee & Snacks", icon: Coffee, color: "#B45309" },
  { id: "transport", label: "Transport", icon: Car, color: "#3B82F6" },
  { id: "utilities", label: "Bills & Utilities", icon: Zap, color: "#EAB308" },
  { id: "housing", label: "Rent & Mortgage", icon: Home, color: "#6366F1" },
  { id: "entertainment", label: "Gaming & Fun", icon: Gamepad2, color: "#8B5CF6" },
  { id: "streaming", label: "Subscriptions", icon: Tv, color: "#EC4899" },
  { id: "shopping", label: "Shopping", icon: ShoppingBag, color: "#14B8A6" },
  { id: "social", label: "Socializing", icon: Users, color: "#F43F5E" },
  { id: "hobbies", label: "Hobbies & Crafts", icon: Sparkles, color: "#A855F7" },
  { id: "travel", label: "Travel & Vacation", icon: Plane, color: "#06B6D4" },
  { id: "health", label: "Medical & Pharmacy", icon: HeartPulse, color: "#10B981" },
  { id: "fitness", label: "Gym & Fitness", icon: Dumbbell, color: "#059669" },
  { id: "grooming", label: "Personal Care", icon: Scissors, color: "#D946EF" },
  { id: "pets", label: "Pet Care", icon: PawPrint, color: "#84CC16" },
  { id: "education", label: "Learning & Books", icon: BookOpen, color: "#2563EB" },
  { id: "work", label: "Work & Business", icon: Briefcase, color: "#475569" },
  { id: "savings", label: "Savings & Deposits", icon: PiggyBank, color: "#22C55E" },
  { id: "taxes", label: "Taxes & Levies", icon: Landmark, color: "#64748B" },
  { id: "emergency", label: "Emergency Fund", icon: ShieldAlert, color: "#DC2626" },
  { id: "maintenance", label: "Home Repairs", icon: Hammer, color: "#78350F" },
  { id: "gifts", label: "Gifts & Donations", icon: Gift, color: "#FB7185" },
  { id: "baby", label: "Baby & Childcare", icon: Baby, color: "#F472B6" },
  { id: "insurance", label: "Insurance", icon: ShieldCheck, color: "#0EA5E9" },
  { id: "clothing", label: "Apparel & Shoes", icon: ShoppingCart, color: "#EC4899" },
  { id: "vices", label: "Alcohol & Tobacco", icon: Wine, color: "#9F1239" },
  { id: "car-maintenance", label: "Vehicle Repair", icon: Wrench, color: "#475569" },
  { id: "legal", label: "Legal & Professional", icon: Scale, color: "#1E3A8A" },
  { id: "investing", label: "Stocks & Crypto", icon: TrendingUp, color: "#15803D" },
  { id: "rentals", label: "Storage & Rentals", icon: KeyRound, color: "#7C3AED" },
  { id: "tuition", label: "School Fees & Tuition", icon: GraduationCap, color: "#1D4ED8" },
  { id: "gadgets", label: "Electronics & Tech", icon: Laptop, color: "#0F172A" },
  { id: "charity", label: "Alms & Charity", icon: Heart, color: "#BE123C" },
  { id: "creative", label: "Art & Design Gear", icon: Brush, color: "#C026D3" },
  { id: "concerts", label: "Events & Tickets", icon: Ticket, color: "#EA580C" },
  { id: "laundry", label: "Dry Cleaning", icon: RefreshCw, color: "#06B6D4" },
  { id: "debt", label: "Loan Repayment", icon: Coins, color: "#B45309" },
  { id: "supplements", label: "Vitamins & Health", icon: Activity, color: "#047857" },
  { id: "unplanned", label: "Spontaneous Spends", icon: AlertTriangle, color: "#EAB308" },
  { id: "cinema", label: "Movies & Theater", icon: Radio, color: "#701A75" },
  { id: "renovation", label: "Home Improvement", icon: Construction, color: "#CA8A04" },
  { id: "hunting", label: "Outdoor & Camping", icon: Crosshair, color: "#166534" },
];

export const CONSTELLATION_NAMES = [
  "Andromeda",
  "Antlia",
  "Apus",
  "Aquarius",
  "Aquila",
  "Ara",
  "Aries",
  "Auriga",
  "Bootes",
  "Caelum",
  "Camelopardalis",
  "Cancer",
  "Canes Venatici",
  "Canis Major",
  "Canis Minor",
  "Capricornus",
  "Carina",
  "Cassiopeia",
  "Centaurus",
  "Cepheus",
  "Cetus",
  "Chamaeleon",
  "Circinus",
  "Columba",
  "Coma Berenices",
  "Corona Australis",
  "Corona Borealis",
  "Corvus",
  "Crater",
  "Crux",
  "Cygnus",
  "Delphinus",
  "Dorado",
  "Draco",
  "Equuleus",
  "Eridanus",
  "Fornax",
  "Gemini",
  "Grus",
  "Hercules",
  "Horologium",
  "Hydra",
  "Hydrus",
  "Indus",
  "Lacerta",
  "Leo",
  "Leo Minor",
  "Lepus",
  "Libra",
  "Lupus",
  "Lynx",
  "Lyra",
  "Mensa",
  "Microscopium",
  "Monoceros",
  "Musca",
  "Norma",
  "Octans",
  "Ophiuchus",
  "Orion",
  "Pavo",
  "Pegasus",
  "Perseus",
  "Phoenix",
  "Pictor",
  "Pisces",
  "Piscis Austrinus",
  "Puppis",
  "Pyxis",
  "Reticulum",
  "Sagitta",
  "Sagittarius",
  "Scorpius",
  "Sculptor",
  "Scutum",
  "Serpens",
  "Sextans",
  "Taurus",
  "Telescopium",
  "Triangulum",
  "Triangulum Australe",
  "Tucana",
  "Ursa Major",
  "Ursa Minor",
  "Vela",
  "Virgo",
  "Volans",
  "Vulpecula"
];