import { StyleSheet } from "react-native";
import { MD3Theme } from "react-native-paper";

export const getHomeStyles = (theme: MD3Theme) => StyleSheet.create({
  mainContainer: {
    padding: 20,
    gap: 24,
    position: "relative",
  },
  screenBackground: {
    flex: 1,
    backgroundColor: theme.colors.background,
  },
  scrollContainer: {
    paddingBottom: 40,
  },
  categoryLiquidShape1: {
    position: "absolute",
    width: 200,
    height: 200,
    borderRadius: 100,
    backgroundColor: theme.colors.primary,
    opacity: 0.16,
    top: 30,
    right: -40,
  },
  categoryLiquidShape2: {
    position: "absolute",
    width: 150,
    height: 150,
    borderRadius: 75,
    backgroundColor: theme.colors.tertiary || "#A855F7",
    opacity: 0.12,
    bottom: 120,
    left: -50,
  },
  categoryLiquidShape3: {
    position: "absolute",
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: theme.colors.secondary,
    opacity: 0.08,
    top: "50%",
    right: "15%",
  },
  categoryGlassOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: theme.colors.background,
    opacity: 0.2,
  },
  heroCard: {
    position: "relative",
    padding: 24,
    borderRadius: theme.roundness * 4,
    backgroundColor: theme.dark
      ? "rgba(23, 25, 37, 0.65)"
      : "rgba(255, 255, 255, 0.55)",
    borderWidth: 1,
    borderColor: theme.dark
      ? "rgba(255, 255, 255, 0.08)"
      : "rgba(255, 255, 255, 0.6)",
    overflow: "hidden",
    marginTop: 10,
    justifyContent: "space-between",
    minHeight: 190,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 16 },
    shadowOpacity: 0.12,
    shadowRadius: 28,
    elevation: 0,
  },
  heroLiquidShape1: {
    position: "absolute",
    width: 140,
    height: 140,
    borderRadius: 70,
    backgroundColor: theme.colors.primary,
    opacity: 0.18,
    top: -40,
    right: -20,
  },
  heroLiquidShape2: {
    position: "absolute",
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: theme.colors.secondary,
    opacity: 0.15,
    bottom: -30,
    left: -10,
  },
  heroGlassOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: theme.colors.surfaceVariant,
    opacity: 0.35,
  },
  heroHeaderRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    zIndex: 1,
    marginBottom: 4,
  },
  liveIndicator: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(255, 255, 255, 0.4)",
    paddingVertical: 3,
    paddingHorizontal: 8,
    borderRadius: 99,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: "rgba(255, 255, 255, 0.5)",
  },
  liveIndicatorPulse: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: theme.colors.primary,
    marginRight: 4,
  },
  liveText: {
    fontWeight: "700",
    letterSpacing: 0.5,
    color: theme.colors.onSurface,
  },
  heroSpendSection: {
    zIndex: 1,
    marginTop: 12,
    marginBottom: 8,
  },
  heroHorizontalDivider: {
    height: StyleSheet.hairlineWidth * 1.5,
    backgroundColor: theme.colors.surfaceVariant,
    marginVertical: 12,
    opacity: 0.5,
    zIndex: 1,
  },
  heroFooterRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    zIndex: 1,
    marginTop: 4,
  },
  heroFooterBudgetBlock: {
    flex: 1,
    marginRight: 16,
  },
  heroLabel: {
    color: theme.colors.primary,
    fontWeight: "800",
    letterSpacing: 1.5,
  },
  heroSubLabel: {
    color: theme.colors.onSurfaceVariant,
    fontWeight: "800",
    letterSpacing: 1.2,
    fontSize: 10,
    textTransform: "uppercase",
    marginBottom: 4,
  },
  heroSubLabelSmallStacked: {
    color: theme.colors.onSurfaceVariant,
    fontWeight: "800",
    letterSpacing: 1.0,
    fontSize: 10,
    textTransform: "uppercase",
    marginBottom: 2,
  },
  heroAmount: {
    color: theme.colors.onSurface,
    fontWeight: "800",
    letterSpacing: -1,
  },
  heroBudgetAmountStacked: {
    color: theme.colors.onSurface,
    fontWeight: "700",
    letterSpacing: -0.5,
  },
  pillBadge: {
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: theme.colors.secondaryContainer,
    paddingVertical: 5,
    paddingHorizontal: 12,
    borderRadius: 99,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: theme.colors.surfaceVariant,
    zIndex: 1,
    marginTop: 6,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
  },
  pillText: {
    color: theme.colors.onSecondaryContainer,
    fontWeight: "700",
  },
  sectionContainer: {
    flexDirection: "column",
  },
  sectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 10,
    paddingHorizontal: 4,
  },
  sectionTitle: {
    color: theme.colors.onSurface,
    fontWeight: "800",
    letterSpacing: -0.4,
  },
  headerCounterText: {
    color: theme.colors.primary,
    fontWeight: "700",
  },
  glassCard: {
    backgroundColor: theme.dark
      ? "rgba(23, 25, 37, 0.65)"
      : "rgba(255, 255, 255, 0.55)",
    borderRadius: theme.roundness * 4,
    padding: 18,
    borderWidth: 1,
    borderColor: theme.dark
      ? "rgba(255, 255, 255, 0.08)"
      : "rgba(255, 255, 255, 0.6)",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 16 },
    shadowOpacity: 0.1,
    shadowRadius: 24,
    elevation: 0,
  },
  glassCardList: {
    backgroundColor: theme.dark
      ? "rgba(23, 25, 37, 0.65)"
      : "rgba(255, 255, 255, 0.55)",
    borderRadius: theme.roundness * 4,
    borderWidth: 1,
    borderColor: theme.dark
      ? "rgba(255, 255, 255, 0.08)"
      : "rgba(255, 255, 255, 0.6)",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 16 },
    shadowOpacity: 0.1,
    shadowRadius: 24,
    elevation: 0,
    overflow: "hidden",
  },
  progressItemRow: {
    marginBottom: 16,
  },
  progressHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  progressBarWrapper: {
    paddingVertical: 2,
  },
  progressBarLine: {
    height: 8,
    borderRadius: 99,
  },
  listItemStyle: {
    paddingVertical: 10,
    paddingHorizontal: 12,
  },
  listSeparator: {
    height: StyleSheet.hairlineWidth,
    backgroundColor: theme.colors.surfaceVariant,
    marginLeft: 68,
    opacity: 0.8,
  },
  iconWrapperCategory: {
    width: 42,
    height: 42,
    borderRadius: theme.roundness * 2,
    backgroundColor: "rgba(103, 80, 164, 0.08)",
    justifyContent: "center",
    alignItems: "center",
    marginLeft: 2,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: "rgba(103, 80, 164, 0.15)",
  },
  iconWrapperExpense: {
    width: 42,
    height: 42,
    borderRadius: theme.roundness * 2,
    backgroundColor: "rgba(103, 80, 164, 0.08)",
    justifyContent: "center",
    alignItems: "center",
    marginLeft: 2,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: "rgba(103, 80, 164, 0.15)",
  },
  chevronWrapper: {
    justifyContent: "center",
    alignItems: "center",
    paddingRight: 6,
  },
  itemTitleText: {
    fontWeight: "700",
    color: theme.colors.onSurface,
  },
  itemDescriptionText: {
    color: theme.colors.onSurfaceVariant,
    marginTop: 3,
    fontWeight: "500",
  },
  mutedText: {
    color: theme.colors.onSurfaceVariant,
    fontWeight: "700",
  },
  iosActionButton: {
    borderRadius: theme.roundness * 2,
    marginTop: 6,
  },
  iosActionLabel: {
    fontWeight: "700",
  },
});

export const getCategoriesStyles = (theme: MD3Theme) => StyleSheet.create({
  mainContainer: {
    flex: 1,
    backgroundColor: theme.colors.background,
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 24,
    position: "relative",
  },
  categoryLiquidShape1: {
    position: "absolute",
    width: 200,
    height: 200,
    borderRadius: 100,
    backgroundColor: theme.colors.primary,
    opacity: 0.16,
    top: 30,
    right: -40,
  },
  categoryLiquidShape2: {
    position: "absolute",
    width: 150,
    height: 150,
    borderRadius: 75,
    backgroundColor: theme.colors.tertiary || "#A855F7",
    opacity: 0.12,
    bottom: 120,
    left: -50,
  },
  categoryLiquidShape3: {
    position: "absolute",
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: theme.colors.secondary,
    opacity: 0.08,
    top: "50%",
    right: "15%",
  },
  categoryGlassOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: theme.colors.background,
    opacity: 0.2,
  },
  sortActiveHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: theme.dark
      ? "rgba(30, 32, 48, 0.7)"
      : "rgba(255, 255, 255, 0.7)",
    borderRadius: theme.roundness * 3,
    paddingVertical: 12,
    paddingHorizontal: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: theme.dark
      ? "rgba(255, 255, 255, 0.08)"
      : "rgba(255, 255, 255, 0.5)",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.05,
    shadowRadius: 16,
    zIndex: 2,
  },
  sortStatusGroup: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  sortStatusLabel: {
    color: theme.colors.onSurfaceVariant,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  sortBadge: {
    backgroundColor: theme.dark
      ? "rgba(103, 80, 164, 0.15)"
      : "rgba(103, 80, 164, 0.08)",
    paddingVertical: 3,
    paddingHorizontal: 10,
    borderRadius: 8,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: "rgba(103, 80, 164, 0.2)",
  },
  sortBadgeText: {
    color: theme.colors.primary,
    fontWeight: "800",
    letterSpacing: 0.2,
  },
  sortButton: {
    paddingVertical: 4,
    paddingHorizontal: 6,
    borderRadius: 8,
  },
  sortButtonLabel: {
    fontWeight: "700",
    color: theme.colors.primary,
  },
  modalBackdrop: {
    margin: 0,
    justifyContent: "flex-end",
    backgroundColor: "rgba(0,0,0,0.5)",
  },
  modalContent: {
    gap: 22,
    paddingTop: 10,
    paddingBottom: 36,
    paddingHorizontal: 24,
    backgroundColor: theme.dark
      ? "rgba(18, 20, 32, 1)"
      : "rgba(255, 255, 255, 1)",
    borderTopLeftRadius: 36,
    borderTopRightRadius: 36,
    borderWidth: 1,
    borderColor: theme.dark
      ? "rgba(255, 255, 255, 0.1)"
      : "rgba(255, 255, 255, 0.7)",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: -12 },
    shadowOpacity: 0.18,
    shadowRadius: 32,
  },
  sheetHandle: {
    width: 38,
    height: 5,
    borderRadius: 99,
    backgroundColor: theme.dark ? "rgba(255, 255, 255, 0.15)" : "rgba(0,0,0,0.12)",
    alignSelf: "center",
    marginBottom: 8,
  },
  modalTitle: {
    fontWeight: "800",
    color: theme.colors.onSurface,
    textAlign: "center",
    letterSpacing: -0.3,
    marginBottom: 6,
  },
  pickerContainer: {
    gap: 10,
  },
  pickerLabel: {
    fontWeight: "800",
    color: theme.colors.primary,
    textTransform: "uppercase",
    letterSpacing: 1.2,
    paddingLeft: 4,
  },
  pickerWrapper: {
    backgroundColor: theme.dark ? "rgba(0, 0, 0, 0.2)" : "rgba(0, 0, 0, 0.02)",
    borderRadius: theme.roundness * 2.5,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: theme.dark
      ? "rgba(255, 255, 255, 0.08)"
      : "rgba(0, 0, 0, 0.06)",
  },
  picker: {
    color: theme.colors.onSurface,
  },
  modalButtonsContainer: {
    gap: 12,
    marginTop: 14,
  },
  modalActionButton: {
    borderRadius: theme.roundness * 3,
    paddingVertical: 8,
  },
  listContainer: {
    flex: 1,
    backgroundColor: theme.dark
      ? "rgba(23, 25, 37, 0.65)"
      : "rgba(255, 255, 255, 0.55)",
    borderRadius: theme.roundness * 4,
    borderWidth: 1,
    borderColor: theme.dark
      ? "rgba(255, 255, 255, 0.08)"
      : "rgba(255, 255, 255, 0.6)",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 16 },
    shadowOpacity: 0.1,
    shadowRadius: 24,
    overflow: "hidden",
    zIndex: 2,
    padding: 4,
  },
  listItemWrapper: {
    borderRadius: theme.roundness * 3,
    overflow: "hidden",
  },
  listItemInner: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 14,
    paddingHorizontal: 14,
  },
  itemTextContainer: {
    flex: 1,
    marginLeft: 14,
    justifyContent: "center",
  },
  itemTitleText: {
    fontWeight: "700",
    color: theme.colors.onSurface,
    letterSpacing: -0.1,
  },
  itemDescriptionText: {
    color: theme.colors.onSurfaceVariant,
    marginTop: 4,
    fontWeight: "600",
    opacity: 0.82,
  },
  iconWrapper: {
    width: 42,
    height: 42,
    borderRadius: theme.roundness * 2.2,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 4,
  },
  chevronWrapper: {
    justifyContent: "center",
    alignItems: "center",
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: theme.dark ? "rgba(255,255,255,0.03)" : "rgba(0,0,0,0.02)",
  },
  listSeparator: {
    height: 1,
    backgroundColor: theme.dark ? "rgba(255, 255, 255, 0.04)" : "rgba(0, 0, 0, 0.03)",
    marginHorizontal: 12,
  },
  emptyContainer: {
    paddingVertical: 56,
    paddingHorizontal: 24,
    alignItems: "center",
    justifyContent: "center",
    zIndex: 2,
  },
  emptyText: {
    textAlign: "center",
    color: theme.colors.onSurfaceVariant,
    fontWeight: "600",
  },
  buttonsContainer: {
    flexDirection: "row",
    justifyContent: "flex-end",
    marginTop: "auto",
    paddingTop: 16,
    zIndex: 10,
  },
  newCategoryButton: {
    borderRadius: theme.roundness * 2,
    paddingHorizontal: 8,
  },
});

export const getCameraStyles = (theme: MD3Theme) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'black',
  },
  centerContent: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  message: {
    textAlign: 'center',
    paddingBottom: 10,
    color: 'white',
  },
  topContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    flexDirection: 'row',
    justifyContent: 'flex-end',
    paddingHorizontal: 24,
    zIndex: 1,
  },
  buttonContainer: {
    position: 'absolute',
    bottom: 32,
    left: 0,
    right: 0,
    flexDirection: 'row',
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: 'transparent',
    paddingHorizontal: 32,
    zIndex: 1,
  },
  button: {
    height: 44,
    width: 44,
    borderRadius: 30,
    justifyContent: "center",
    alignItems: 'center',
    backgroundColor: "white",
  },
  iconButton: {
    height: 44,
    width: 44,
    borderRadius: 22,
    justifyContent: "center",
    alignItems: 'center',
    backgroundColor: "white",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
});

export const getExpensesStyles = (theme: MD3Theme) => StyleSheet.create({
  mainContainer: {
    flex: 1,
    backgroundColor: theme.colors.background,
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 24,
    position: "relative",
  },
  categoryLiquidShape1: {
    position: "absolute",
    width: 200,
    height: 200,
    borderRadius: 100,
    backgroundColor: theme.colors.primary,
    opacity: 0.16,
    top: 30,
    right: -40,
  },
  categoryLiquidShape2: {
    position: "absolute",
    width: 150,
    height: 150,
    borderRadius: 75,
    backgroundColor: theme.colors.tertiary || "#A855F7",
    opacity: 0.12,
    bottom: 120,
    left: -50,
  },
  categoryLiquidShape3: {
    position: "absolute",
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: theme.colors.secondary,
    opacity: 0.08,
    top: "50%",
    right: "15%",
  },
  categoryGlassOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: theme.colors.background,
    opacity: 0.2,
  },
  sortActiveHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: theme.dark
      ? "rgba(30, 32, 48, 0.7)"
      : "rgba(255, 255, 255, 0.7)",
    borderRadius: theme.roundness * 3,
    paddingVertical: 12,
    paddingHorizontal: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: theme.dark
      ? "rgba(255, 255, 255, 0.08)"
      : "rgba(255, 255, 255, 0.5)",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.05,
    shadowRadius: 16,
    zIndex: 2,
  },
  sortStatusGroup: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  sortStatusLabel: {
    color: theme.colors.onSurfaceVariant,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  sortBadge: {
    backgroundColor: theme.dark
      ? "rgba(103, 80, 164, 0.15)"
      : "rgba(103, 80, 164, 0.08)",
    paddingVertical: 3,
    paddingHorizontal: 10,
    borderRadius: 8,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: "rgba(103, 80, 164, 0.2)",
  },
  sortBadgeText: {
    color: theme.colors.primary,
    fontWeight: "800",
    letterSpacing: 0.2,
  },
  sortButton: {
    paddingVertical: 4,
    paddingHorizontal: 6,
    borderRadius: 8,
  },
  sortButtonLabel: {
    fontWeight: "700",
    color: theme.colors.primary,
  },
  modalBackdrop: {
    margin: 0,
    justifyContent: "flex-end",
    backgroundColor: "rgba(0,0,0,0.5)",
  },
  modalContent: {
    gap: 22,
    paddingTop: 10,
    paddingBottom: 36,
    paddingHorizontal: 24,
    backgroundColor: theme.dark
      ? "rgba(18, 20, 32, 1)"
      : "rgba(255, 255, 255, 1)",
    borderTopLeftRadius: 36,
    borderTopRightRadius: 36,
    borderWidth: 1,
    borderColor: theme.dark
      ? "rgba(255, 255, 255, 0.1)"
      : "rgba(255, 255, 255, 0.7)",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: -12 },
    shadowOpacity: 0.18,
    shadowRadius: 32,
  },
  sheetHandle: {
    width: 38,
    height: 5,
    borderRadius: 99,
    backgroundColor: theme.dark ? "rgba(255, 255, 255, 0.15)" : "rgba(0,0,0,0.12)",
    alignSelf: "center",
    marginBottom: 8,
  },
  modalTitle: {
    fontWeight: "800",
    color: theme.colors.onSurface,
    textAlign: "center",
    letterSpacing: -0.3,
    marginBottom: 6,
  },
  pickerContainer: {
    gap: 10,
  },
  pickerLabel: {
    fontWeight: "800",
    color: theme.colors.primary,
    textTransform: "uppercase",
    letterSpacing: 1.2,
    paddingLeft: 4,
  },
  pickerWrapper: {
    backgroundColor: theme.dark ? "rgba(0, 0, 0, 0.2)" : "rgba(0, 0, 0, 0.02)",
    borderRadius: theme.roundness * 2.5,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: theme.dark
      ? "rgba(255, 255, 255, 0.08)"
      : "rgba(0, 0, 0, 0.06)",
  },
  picker: {
    color: theme.colors.onSurface,
  },
  modalButtonsContainer: {
    gap: 12,
    marginTop: 14,
  },
  modalActionButton: {
    borderRadius: theme.roundness * 3,
    paddingVertical: 8,
  },
  listContainer: {
    flex: 1,
    backgroundColor: theme.dark
      ? "rgba(23, 25, 37, 0.65)"
      : "rgba(255, 255, 255, 0.55)",
    borderRadius: theme.roundness * 4,
    borderWidth: 1,
    borderColor: theme.dark
      ? "rgba(255, 255, 255, 0.08)"
      : "rgba(255, 255, 255, 0.6)",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 16 },
    shadowOpacity: 0.1,
    shadowRadius: 24,
    overflow: "hidden",
    zIndex: 2,
    padding: 4,
  },
  listItemWrapper: {
    borderRadius: theme.roundness * 3,
    overflow: "hidden",
  },
  listItemInner: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 14,
    paddingHorizontal: 14,
  },
  itemTextContainer: {
    flex: 1,
    marginLeft: 14,
    justifyContent: "center",
  },
  itemTitleText: {
    fontWeight: "700",
    color: theme.colors.onSurface,
    letterSpacing: -0.1,
  },
  itemDescriptionText: {
    color: theme.colors.onSurfaceVariant,
    marginTop: 4,
    fontWeight: "600",
    opacity: 0.82,
  },
  iconWrapper: {
    width: 42,
    height: 42,
    borderRadius: theme.roundness * 2.2,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 4,
  },
  chevronWrapper: {
    justifyContent: "center",
    alignItems: "center",
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: theme.dark ? "rgba(255,255,255,0.03)" : "rgba(0,0,0,0.02)",
  },
  listSeparator: {
    height: 1,
    backgroundColor: theme.dark ? "rgba(255, 255, 255, 0.04)" : "rgba(0, 0, 0, 0.03)",
    marginHorizontal: 12,
  },
  emptyContainer: {
    paddingVertical: 56,
    paddingHorizontal: 24,
    alignItems: "center",
    justifyContent: "center",
    zIndex: 2,
  },
  emptyText: {
    textAlign: "center",
    color: theme.colors.onSurfaceVariant,
    fontWeight: "600",
  },
  buttonsContainer: {
    flexDirection: "row",
    justifyContent: "flex-end",
    marginTop: "auto",
    paddingTop: 16,
    zIndex: 10,
  },
  newCategoryButton: {
    borderRadius: theme.roundness * 2,
    paddingHorizontal: 8,
  },
  listItemStyle: {
    paddingVertical: 8,
    paddingHorizontal: 8,
  },
});

export const getSettingsStyles = (theme: MD3Theme) => StyleSheet.create({
  mainContainer: {
    flex: 1,
    backgroundColor: theme.colors.background,
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 24,
    position: "relative",
  },
  categoryLiquidShape1: {
    position: "absolute",
    width: 220,
    height: 220,
    borderRadius: 110,
    backgroundColor: theme.colors.primary,
    opacity: 0.16,
    top: -30,
    right: -40,
  },
  categoryLiquidShape2: {
    position: "absolute",
    width: 160,
    height: 160,
    borderRadius: 80,
    backgroundColor: theme.colors.tertiary || "#A855F7",
    opacity: 0.12,
    bottom: 80,
    left: -50,
  },
  categoryLiquidShape3: {
    position: "absolute",
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: theme.colors.secondary,
    opacity: 0.08,
    top: "35%",
    right: "15%",
  },
  categoryGlassOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: theme.colors.background,
    opacity: 0.22,
  },
  sectionContainer: {
    gap: 10,
    marginBottom: 20,
  },
  sectionLabel: {
    fontWeight: "800",
    color: theme.colors.onSurface,
    paddingLeft: 4,
    letterSpacing: 1.2,
    textTransform: "uppercase",
  },
  pickerWrapper: {
    backgroundColor: theme.dark
      ? "rgba(0, 0, 0, 0.22)"
      : "rgba(255, 255, 255, 0.45)",
    borderRadius: theme.roundness * 2.5,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: theme.dark
      ? "rgba(255, 255, 255, 0.12)"
      : "rgba(0, 0, 0, 0.1)",
  },
  picker: {
    color: theme.colors.onSurface,
  },
  actionButton: {
    borderRadius: theme.roundness * 3,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: theme.dark ? "rgba(255, 255, 255, 0.08)" : "rgba(0, 0, 0, 0.05)",
  },
  infoCard: {
    backgroundColor: theme.dark
      ? "rgba(255, 255, 255, 0.11)"
      : "rgba(255, 255, 255, 0.78)",
    borderColor: theme.dark
      ? "rgba(255, 255, 255, 0.15)"
      : "rgba(255, 255, 255, 0.75)",
    borderWidth: 1,
    padding: 20,
    borderRadius: theme.roundness * 3.5,
    gap: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.06,
    shadowRadius: 20,
    elevation: 0,
  },
  infoTitle: {
    fontWeight: "800",
    color: theme.colors.onSurface,
    letterSpacing: -0.2,
  },
  textGroup: {
    gap: 6,
  },
  infoText: {
    color: theme.colors.onSurfaceVariant,
    fontWeight: "600",
  },
  socialsRow: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 28,
    paddingVertical: 12,
  },
  socialTouchTarget: {
    padding: 6,
  },
  developerButton: {
    marginTop: 8,
    borderRadius: theme.roundness * 3,
    paddingVertical: 8,
    backgroundColor: theme.colors.primary,
    shadowColor: theme.colors.primary,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.28,
    shadowRadius: 16,
  },
});